name: CI Docker Build

on:
  push:
    branches:
      - dev2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

